name = "NeuroSpikes"
uuid = "74593c1d-37c3-4d7e-aa49-3d03236a38e2"
authors = ["nish <nishs1729@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
